/**
 * blood-supply-review.json -> src/features/anatomy-revision/data/seed/bloodSupply.generated.ts
 *
 *   npm run generate:blood-supply   (from the repo root)
 *
 * Keeps only rows the owner accepted (`review.status === 'accepted'`) and never
 * a landmark: landmarks are parts of bones, and the owner took them out of the
 * blood-supply questions (29 Sep 2026). Arteries a row flags as `unsupported`
 * — named by the draft but backed by no quoted source — are dropped here, so a
 * question can never ask for one.
 *
 * The first artery a row lists is its primary supply: the research brief asked
 * for "primary first", and every row's text reads that way. Quotes, sources and
 * the rating's reasoning stay in the JSON; the bundle carries only what a
 * question or a card shows.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface ReviewRow {
  id: string;
  category: string;
  arteries: string[];
  unsupported?: string[];
  rating: 'rich' | 'moderate' | 'poor';
  zone: { text: string } | null;
  review?: { status: string };
}

const ROOT = process.cwd();
const rows: ReviewRow[] = JSON.parse(readFileSync(join(ROOT, 'blood-supply-review.json'), 'utf8'));

const accepted = rows.filter((r) => r.review?.status === 'accepted' && r.category !== 'landmark');
const entries = accepted.map((r) => {
  const arteries = r.arteries.filter((a) => !(r.unsupported ?? []).includes(a));
  const [primary = null, ...assisting] = arteries;
  const zone = r.zone?.text ? { zone: r.zone.text } : {};
  return [r.id, { primary, assisting, rating: r.rating, ...zone }] as const;
});

const body = entries.map(([id, v]) => `  ${JSON.stringify(id)}: ${JSON.stringify(v)},`).join('\n');
const out = `// GENERATED by src/scripts/generateBloodSupplySeed.ts from blood-supply-review.json.
// Do not edit by hand: change the review file and regenerate.
import type { BloodSupply } from '../../types/structure';

export const BLOOD_SUPPLY: Record<string, BloodSupply> = {
${body}
};
`;
writeFileSync(join(ROOT, 'src/features/anatomy-revision/data/seed/bloodSupply.generated.ts'), out);
console.log(`bloodSupply.generated.ts: ${entries.length} structures (${rows.length - accepted.length} not accepted or landmarks left out)`);
