import type { LigamentStructure } from '../../types/structure';

/**
 * Retinacula, aponeuroses, membranes and named tendons — the connective tissue
 * the app kept referring to but did not hold.
 *
 * WHY THIS FILE EXISTS. The attachment reconciliation found 37 bone and
 * landmark claims that could not be corroborated for one reason: the structure
 * they named was not in the dataset. The scaphoid tubercle said "flexor
 * retinaculum attaches here" and there was no flexor retinaculum; Gerdy's
 * tubercle said "iliotibial band inserts here" and there was no IT band. The
 * facts were fine — the dataset simply had a hole where they pointed.
 *
 * WHY NOT structures.ligaments.seed.ts. That file is GENERATED by
 * generateLigamentSeed.ts, and that generator rebuilds only the 32-ligament
 * tranche it is pointed at — running it against the full seed deletes the other
 * 111 entries (confirmed the hard way, 24 Sep 2026). Hand-authored entries live
 * here instead, where a regeneration cannot reach them.
 *
 * WHY category 'ligament'. The Category union has no 'tendon' or 'fascia'
 * member, and the ligament category already carries the menisci and the
 * interosseous membranes, so it is the dataset's bucket for connective tissue
 * generally rather than for ligaments strictly.
 *
 * EVERY ENTRY IS SOURCE-CHECKED. Each was fetched and quoted before it was
 * written; the citations are in connective-source-review.json rather than here,
 * for the same reason the ligament citations are not in their seed — nothing
 * renders `notes`, and the quotes were 22 kB of the entry chunk.
 *
 * NO IMAGES YET. imageIds is empty and eligibility.locate is false for all of
 * them: no plate renders these, and a locate question with no hotspot is
 * unanswerable. They are askable by name and description until plates exist.
 */
export const CONNECTIVE_STRUCTURES: LigamentStructure[] = [
  {
    id: 'flexor-retinaculum',
    name: 'Flexor Retinaculum',
    category: 'ligament',
    region: 'forearm-hand',
    subregion: 'wrist-hand',
    description:
      'A fibrous band on the palmar side of the hand near the wrist. It bridges the carpal arch from the scaphoid tubercle and trapezium on the radial side to the pisiform and the hook of the hamate on the ulnar side, and its deep surface forms the roof of the carpal tunnel.',
    aliases: ['Transverse Carpal Ligament', 'Anterior Annular Ligament'],
    attachmentStructureIds: ['scaphoid-tubercle', 'trapezium', 'pisiform', 'hook-of-hamate', 'carpals'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament', 'retinaculum'],
    clinical: 'The roof of the carpal tunnel — it is this band that is divided in a carpal tunnel release.',
    notes: null,
  },
  {
    id: 'extensor-retinaculum-hand',
    name: 'Extensor Retinaculum of the Hand',
    category: 'ligament',
    region: 'forearm-hand',
    subregion: 'wrist-hand',
    description:
      'A strong fibrous band extending obliquely across the back of the wrist, a thickening of the deep fascia of the forearm that holds the extensor tendons in place. It attaches to the distal radius towards the styloid process and to the pisiform and triquetrum, and not to the ulna — which lets the radius rotate beneath the tendons.',
    aliases: ['Dorsal Carpal Ligament', 'Posterior Annular Ligament'],
    attachmentStructureIds: ['radius', 'radial-styloid-process', 'pisiform', 'triquetrum', 'carpals'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament', 'retinaculum'],
    notes: null,
  },
  {
    id: 'triangular-fibrocartilage-complex',
    name: 'Triangular Fibrocartilage Complex',
    category: 'ligament',
    region: 'forearm-hand',
    subregion: 'wrist-hand',
    description:
      'The main stabiliser of the distal radioulnar joint, formed by the triangular fibrocartilage disc together with the radioulnar and ulnocarpal ligaments. The disc attaches by thick tissue to the base of the ulnar styloid and by thinner tissue to the edge of the radius.',
    aliases: ['TFCC'],
    abbreviation: 'TFCC',
    attachmentStructureIds: ['ulnar-styloid-process', 'ulna', 'radius'],
    jointId: 'distal-radioulnar-joint',
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'hard',
    tags: ['ligament'],
    clinical: 'A common cause of ulnar-sided wrist pain, and the reason a fall on an outstretched hand can hurt on the little-finger side.',
    notes: null,
  },
  {
    id: 'iliotibial-band',
    name: 'Iliotibial Band',
    category: 'ligament',
    region: 'hip-thigh',
    subregion: 'knee',
    description:
      'A longitudinal fibrous reinforcement of the fascia lata down the lateral thigh. It originates at the anterolateral iliac tubercle of the external lip of the iliac crest and inserts at the lateral condyle of the tibia at Gerdy’s tubercle.',
    aliases: ['Iliotibial Tract', 'IT Band', 'Maissiat’s Band'],
    abbreviation: 'ITB',
    attachmentStructureIds: ['iliac-crest', 'gerdys-tubercle', 'lateral-condyle-tibia'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament', 'fascia'],
    clinical: 'Friction at its distal end over the lateral femoral epicondyle is the classic runner’s lateral knee pain.',
    notes: null,
  },
  {
    id: 'patellar-ligament',
    name: 'Patellar Ligament',
    category: 'ligament',
    region: 'hip-thigh',
    subregion: 'knee',
    description:
      'The distal portion of the common tendon of the quadriceps femoris, continued from the patella to the tibial tuberosity. It is called a ligament because it runs bone to bone, though it is the continuation of a tendon.',
    aliases: ['Patellar Tendon'],
    attachmentStructureIds: ['patella', 'tibial-tuberosity', 'tibia'],
    jointId: 'patellofemoral-joint',
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'easy',
    tags: ['ligament'],
    clinical: 'Where the tendon pulls on the growing tibial tuberosity in Osgood-Schlatter disease.',
    notes: null,
  },
  {
    id: 'plantar-fascia',
    name: 'Plantar Fascia',
    category: 'ligament',
    region: 'lower-leg-foot',
    subregion: 'ankle-foot',
    description:
      'The thick connective tissue aponeurosis supporting the arch on the plantar side of the foot. It runs from the tuberosity of the calcaneus forward to the heads of the metatarsal bones.',
    aliases: ['Plantar Aponeurosis'],
    attachmentStructureIds: ['calcaneal-tuberosity', 'calcaneus', 'metatarsals', 'tarsals'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'easy',
    tags: ['ligament', 'fascia'],
    clinical: 'Plantar fasciitis is felt at its calcaneal origin, which is why the first step out of bed hurts most.',
    notes: null,
  },
  {
    id: 'achilles-tendon',
    name: 'Achilles Tendon',
    category: 'ligament',
    region: 'lower-leg-foot',
    subregion: 'ankle-foot',
    description:
      'The thickest tendon in the human body, at the back of the lower leg. It attaches the plantaris, gastrocnemius and soleus muscles to the calcaneus, inserting into the middle part of the back of that bone.',
    aliases: ['Calcaneal Tendon', 'Heel Cord'],
    attachmentStructureIds: ['calcaneal-tuberosity', 'calcaneus'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'easy',
    tags: ['ligament', 'tendon'],
    clinical: 'Ruptures with a sudden push-off; Simmonds’ (Thompson’s) test squeezes the calf to check it is intact.',
    notes: null,
  },
  {
    id: 'inguinal-ligament',
    name: 'Inguinal Ligament',
    category: 'ligament',
    region: 'hip-thigh',
    subregion: 'hip',
    description:
      'A band running from the pubic tubercle to the anterior superior iliac spine, formed by the rolled lower border of the external oblique aponeurosis. It is the boundary between the abdomen and the thigh.',
    aliases: ['Poupart’s Ligament'],
    attachmentStructureIds: ['pubic-tubercle', 'asis', 'pelvis'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament'],
    clinical: 'An inguinal hernia passes above it, a femoral hernia below — which is how the two are told apart on examination.',
    notes: null,
  },
  {
    id: 'iliofemoral-ligament',
    name: 'Iliofemoral Ligament',
    category: 'ligament',
    region: 'hip-thigh',
    subregion: 'hip',
    description:
      'A thick, very tough triangular capsular ligament in front of the hip joint. It attaches superiorly at the anterior inferior iliac spine and the adjacent margin of the acetabulum, and inferiorly at the intertrochanteric line.',
    aliases: ['Y Ligament of Bigelow'],
    attachmentStructureIds: ['aiis', 'intertrochanteric-line', 'pelvis', 'femur'],
    jointId: 'hip-joint',
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament'],
    clinical: 'The strongest ligament in the body; it is what checks hip extension and holds you upright without muscular effort.',
    notes: null,
  },
  {
    id: 'ligamentum-teres-femoris',
    name: 'Ligament of the Head of the Femur',
    category: 'ligament',
    region: 'hip-thigh',
    subregion: 'hip',
    description:
      'Implanted by its apex into the anterosuperior part of the fovea capitis of the femoral head, with its base attached by two bands either side of the acetabular notch. It carries a small artery to the femoral head.',
    aliases: ['Ligamentum Teres', 'Round Ligament of the Femur'],
    attachmentStructureIds: ['femoral-head', 'acetabulum', 'pelvis', 'femur'],
    jointId: 'hip-joint',
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament'],
    clinical: 'Its artery is the main blood supply to the femoral head in childhood, which is why a hip that loses it can go on to avascular necrosis.',
    notes: null,
  },
  {
    id: 'alar-ligaments',
    name: 'Alar Ligaments',
    category: 'ligament',
    region: 'back-core',
    subregion: 'neck',
    description:
      'Paired ligaments connecting the dens of the axis to tubercles on the medial side of each occipital condyle. They are the main check on rotation of the head.',
    aliases: [],
    attachmentStructureIds: ['dens-odontoid-process', 'axis-c2', 'occipital-bone'],
    jointId: 'atlantoaxial-joint',
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'hard',
    tags: ['ligament'],
    clinical: 'Tested in the craniocervical screen before cervical mobilisation, because failure here leaves the head under-restrained on the neck.',
    notes: null,
  },
  {
    id: 'transverse-ligament-of-atlas',
    name: 'Transverse Ligament of the Atlas',
    category: 'ligament',
    region: 'back-core',
    subregion: 'neck',
    description:
      'A broad, tough ligament arching across the ring of the atlas behind the dens, keeping the dens in contact with the anterior arch. It attaches either side onto a small prominent tubercle on the medial aspect of each lateral mass of the atlas.',
    aliases: [],
    attachmentStructureIds: ['lateral-mass-atlas', 'atlas-c1', 'dens-odontoid-process'],
    jointId: 'atlantoaxial-joint',
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'hard',
    tags: ['ligament'],
    clinical: 'If it fails the dens is no longer anchored and can travel up the cervical spine — the reason this is screened before any upper cervical technique.',
    notes: null,
  },
  {
    id: 'intertransverse-ligaments',
    name: 'Intertransverse Ligaments',
    category: 'ligament',
    region: 'back-core',
    subregion: 'spine',
    description:
      'Weak, sheet-like ligaments interconnecting adjacent transverse processes in the thoracic spine, and adjacent accessory processes in the lumbar spine.',
    aliases: [],
    attachmentStructureIds: ['transverse-process', 'thoracic-vertebrae', 'lumbar-vertebrae'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament'],
    notes: null,
  },
  {
    id: 'linea-alba',
    name: 'Linea Alba',
    category: 'ligament',
    region: 'back-core',
    subregion: 'torso',
    description:
      'The fibrous midline of the abdominal wall, formed where the aponeuroses of the flat abdominal muscles interlace. It attaches to the xiphoid process superiorly and to the pubic symphysis inferiorly.',
    aliases: [],
    attachmentStructureIds: ['xiphoid-process', 'sternum', 'pubis'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament', 'fascia'],
    clinical: 'It widens in diastasis recti, when the two rectus bellies separate either side of it.',
    notes: null,
  },
  {
    id: 'costal-cartilage',
    name: 'Costal Cartilage',
    category: 'ligament',
    region: 'back-core',
    subregion: 'torso',
    description:
      'Bars of hyaline cartilage that prolong the ribs forward and give the thoracic wall its elasticity. The first seven pairs connect with the sternum; the next three each articulate with the lower border of the cartilage above; the last two end in the abdominal wall.',
    aliases: ['Rib Cartilage'],
    attachmentStructureIds: ['ribs', 'sternum'],
    jointId: 'sternocostal-joint',
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament'],
    clinical: 'Inflammation here is costochondritis, a common cause of chest pain that is reproduced by pressing on the joint.',
    notes: null,
  },
];
