import type { LigamentStructure } from '../../types/structure';

/**
 * Retinacula, aponeuroses, membranes and named tendons — the connective tissue
 * the app kept referring to but did not hold.
 *
 * WHY THIS FILE EXISTS. The attachment reconciliation found 37 bone and
 * landmark claims that could not be corroborated for one reason: the structure
 * they named was not in the dataset. The scaphoid tubercle said "flexor
 * retinaculum attaches here" and there was no flexor retinaculum; Gerdy's
 * tubercle said "iliotibial band inserts here" and there was no IT band. The
 * facts were fine — the dataset simply had a hole where they pointed.
 *
 * WHY NOT structures.ligaments.seed.ts. That file is GENERATED by
 * generateLigamentSeed.ts, and that generator rebuilds only the 32-ligament
 * tranche it is pointed at — running it against the full seed deletes the other
 * 111 entries (confirmed the hard way, 24 Sep 2026). Hand-authored entries live
 * here instead, where a regeneration cannot reach them.
 *
 * WHY category 'ligament'. The Category union has no 'tendon' or 'fascia'
 * member, and the ligament category already carries the menisci and the
 * interosseous membranes, so it is the dataset's bucket for connective tissue
 * generally rather than for ligaments strictly.
 *
 * EVERY ENTRY IS SOURCE-CHECKED. Each was fetched and quoted before it was
 * written; the citations are in connective-source-review.json rather than here,
 * for the same reason the ligament citations are not in their seed — nothing
 * renders `notes`, and the quotes were 22 kB of the entry chunk.
 *
 * NO IMAGES YET, for the retinacula, aponeuroses and tendons: imageIds is empty
 * and eligibility.locate is false, because no plate renders them and a locate
 * question with no hotspot is unanswerable. They are askable by name and
 * description until plates exist.
 *
 * THE BURIED LIGAMENTS (4 Oct 2026) are the exception, at the foot of the list:
 * atlas ligaments tranche 2 rendered and could not trace, because they lie
 * under bone or under other ligaments. They are hand-authored here for the
 * reason above (a regeneration cannot reach them), they DO have plates
 * (ligament-buried.spec.json), and their attachments were fetched and quoted
 * before they were written — the citations are in
 * ligament-attachment-corrections.json and docs/ligament-attachments-review.md.
 * Their names are the atlas's own, in its sentence case, like the generated
 * ligament seed. Descriptions and the one clinical note are drafted, not
 * source-checked, as /sources says of every ligament.
 */
export const CONNECTIVE_STRUCTURES: LigamentStructure[] = [
  {
    id: 'flexor-retinaculum',
    name: 'Flexor retinaculum',
    category: 'ligament',
    region: 'forearm-hand',
    subregion: 'wrist-hand',
    description:
      'A fibrous band on the palmar side of the hand near the wrist. It bridges the carpal arch from the scaphoid tubercle and trapezium on the radial side to the pisiform and the hook of the hamate on the ulnar side, and its deep surface forms the roof of the carpal tunnel.',
    aliases: ['Transverse Carpal Ligament', 'Anterior Annular Ligament'],
    attachmentStructureIds: ['scaphoid-tubercle', 'trapezium', 'pisiform', 'hook-of-hamate'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament', 'retinaculum'],
    clinical: 'The roof of the carpal tunnel — it is this band that is divided in a carpal tunnel release.',
    notes: null,
  },
  {
    id: 'extensor-retinaculum-hand',
    name: 'Extensor retinaculum of hand',
    category: 'ligament',
    region: 'forearm-hand',
    subregion: 'wrist-hand',
    description:
      'A strong fibrous band extending obliquely across the back of the wrist, a thickening of the deep fascia of the forearm that holds the extensor tendons in place. It attaches to the distal radius towards the styloid process and to the pisiform and triquetrum, and not to the ulna — which lets the radius rotate beneath the tendons.',
    aliases: ['Dorsal Carpal Ligament', 'Posterior Annular Ligament'],
    attachmentStructureIds: ['radial-styloid-process', 'pisiform', 'triquetrum'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament', 'retinaculum'],
    notes: null,
  },
  {
    id: 'triangular-fibrocartilage-complex',
    name: 'Triangular fibrocartilage complex',
    category: 'ligament',
    region: 'forearm-hand',
    subregion: 'wrist-hand',
    description:
      'The main stabiliser of the distal radioulnar joint, formed by the triangular fibrocartilage disc together with the radioulnar and ulnocarpal ligaments. The disc attaches by thick tissue to the base of the ulnar styloid and by thinner tissue to the edge of the radius.',
    aliases: ['TFCC'],
    abbreviation: 'TFCC',
    attachmentStructureIds: ['ulnar-styloid-process', 'radius'],
    jointId: 'distal-radioulnar-joint',
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'hard',
    tags: ['ligament'],
    clinical: 'A common cause of ulnar-sided wrist pain, and the reason a fall on an outstretched hand can hurt on the little-finger side.',
    notes: null,
  },
  {
    id: 'iliotibial-band',
    name: 'Iliotibial band',
    category: 'ligament',
    region: 'hip-thigh',
    subregion: 'knee',
    description:
      'A longitudinal fibrous reinforcement of the fascia lata down the lateral thigh. It originates at the anterolateral iliac tubercle of the external lip of the iliac crest and inserts at the lateral condyle of the tibia at Gerdy’s tubercle.',
    aliases: ['Iliotibial Tract', 'IT Band', 'Maissiat’s Band'],
    abbreviation: 'ITB',
    attachmentStructureIds: ['iliac-crest', 'gerdys-tubercle', 'lateral-condyle-tibia'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament', 'fascia'],
    clinical: 'Friction at its distal end over the lateral femoral epicondyle is the classic runner’s lateral knee pain.',
    notes: null,
  },
  {
    id: 'patellar-ligament',
    name: 'Patellar ligament',
    category: 'ligament',
    region: 'hip-thigh',
    subregion: 'knee',
    description:
      'The distal portion of the common tendon of the quadriceps femoris, continued from the patella to the tibial tuberosity. It is called a ligament because it runs bone to bone, though it is the continuation of a tendon.',
    aliases: ['Patellar Tendon'],
    attachmentStructureIds: ['patella', 'tibial-tuberosity'],
    jointId: 'patellofemoral-joint',
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'easy',
    tags: ['ligament'],
    clinical: 'Where the tendon pulls on the growing tibial tuberosity in Osgood-Schlatter disease.',
    notes: null,
  },
  {
    id: 'plantar-fascia',
    name: 'Plantar fascia',
    category: 'ligament',
    region: 'lower-leg-foot',
    subregion: 'ankle-foot',
    description:
      'The thick connective tissue aponeurosis supporting the arch on the plantar side of the foot. It runs from the tuberosity of the calcaneus forward to the heads of the metatarsal bones.',
    aliases: ['Plantar Aponeurosis'],
    attachmentStructureIds: ['calcaneal-tuberosity', 'calcaneus', 'metatarsals'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'easy',
    tags: ['ligament', 'fascia'],
    clinical: 'Plantar fasciitis is felt at its calcaneal origin, which is why the first step out of bed hurts most.',
    notes: null,
  },
  {
    id: 'achilles-tendon',
    name: 'Achilles tendon',
    category: 'ligament',
    region: 'lower-leg-foot',
    subregion: 'ankle-foot',
    description:
      'The thickest tendon in the human body, at the back of the lower leg. It attaches the plantaris, gastrocnemius and soleus muscles to the calcaneus, inserting into the middle part of the back of that bone.',
    aliases: ['Calcaneal Tendon', 'Heel Cord'],
    attachmentStructureIds: ['calcaneal-tuberosity', 'calcaneus'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'easy',
    tags: ['ligament', 'tendon'],
    clinical: 'Ruptures with a sudden push-off; Simmonds’ (Thompson’s) test squeezes the calf to check it is intact.',
    notes: null,
  },
  {
    id: 'inguinal-ligament',
    name: 'Inguinal ligament',
    category: 'ligament',
    region: 'hip-thigh',
    subregion: 'hip',
    description:
      'A band running from the pubic tubercle to the anterior superior iliac spine, formed by the rolled lower border of the external oblique aponeurosis. It is the boundary between the abdomen and the thigh.',
    aliases: ['Poupart’s Ligament'],
    attachmentStructureIds: ['pubic-tubercle', 'asis'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament'],
    clinical: 'An inguinal hernia passes above it, a femoral hernia below — which is how the two are told apart on examination.',
    notes: null,
  },
  {
    id: 'iliofemoral-ligament',
    name: 'Iliofemoral ligament',
    category: 'ligament',
    region: 'hip-thigh',
    subregion: 'hip',
    description:
      'A thick, very tough triangular capsular ligament in front of the hip joint. It attaches superiorly at the anterior inferior iliac spine and the adjacent margin of the acetabulum, and inferiorly at the intertrochanteric line.',
    aliases: ['Y Ligament of Bigelow'],
    attachmentStructureIds: ['aiis', 'acetabulum', 'intertrochanteric-line'],
    jointId: 'hip-joint',
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament'],
    clinical: 'The strongest ligament in the body; it is what checks hip extension and holds you upright without muscular effort.',
    notes: null,
  },
  {
    id: 'alar-ligaments',
    name: 'Alar ligaments',
    category: 'ligament',
    region: 'back-core',
    subregion: 'neck',
    description:
      'Paired ligaments connecting the dens of the axis to tubercles on the medial side of each occipital condyle. They are the main check on rotation of the head.',
    aliases: [],
    attachmentStructureIds: ['dens-odontoid-process', 'occipital-bone'],
    jointId: 'atlantoaxial-joint',
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'hard',
    tags: ['ligament'],
    clinical: 'Tested in the craniocervical screen before cervical mobilisation, because failure here leaves the head under-restrained on the neck.',
    notes: null,
  },
  {
    id: 'transverse-ligament-of-atlas',
    name: 'Transverse ligament of atlas',
    category: 'ligament',
    region: 'back-core',
    subregion: 'neck',
    description:
      'A broad, tough ligament arching across the ring of the atlas behind the dens, keeping the dens in contact with the anterior arch. It attaches either side onto a small prominent tubercle on the medial aspect of each lateral mass of the atlas.',
    aliases: [],
    attachmentStructureIds: ['lateral-mass-atlas', 'dens-odontoid-process'],
    jointId: 'atlantoaxial-joint',
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'hard',
    tags: ['ligament'],
    clinical: 'If it fails the dens is no longer anchored and can travel up the cervical spine — the reason this is screened before any upper cervical technique.',
    notes: null,
  },
  {
    id: 'intertransverse-ligaments',
    name: 'Intertransverse ligaments',
    category: 'ligament',
    region: 'back-core',
    subregion: 'spine',
    description:
      'Weak, sheet-like ligaments interconnecting adjacent transverse processes in the thoracic spine, and adjacent accessory processes in the lumbar spine.',
    aliases: [],
    attachmentStructureIds: ['transverse-process', 'thoracic-vertebrae', 'lumbar-vertebrae'],
    imageIds: [],
    // Locate since 4 Oct 2026: the atlas models these as bare edges with a Skin
    // modifier, which the renderer used to draw as nothing. They were never
    // buried; see skinned_copy in renderLigamentPlates.py.
    eligibility: { flashcard: true, mcq: true, locate: true },
    difficulty: 'medium',
    tags: ['ligament'],
    notes: null,
  },
  {
    id: 'linea-alba',
    name: 'Linea alba',
    category: 'ligament',
    region: 'back-core',
    subregion: 'torso',
    description:
      'The fibrous midline of the abdominal wall, formed where the aponeuroses of the flat abdominal muscles interlace. It attaches to the xiphoid process superiorly and to the pubic symphysis inferiorly.',
    aliases: [],
    attachmentStructureIds: ['xiphoid-process', 'pubis'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament', 'fascia'],
    clinical: 'It widens in diastasis recti, when the two rectus bellies separate either side of it.',
    notes: null,
  },
  {
    id: 'costal-cartilage',
    name: 'Costal cartilage',
    category: 'ligament',
    region: 'back-core',
    subregion: 'torso',
    description:
      'Bars of hyaline cartilage that prolong the ribs forward and give the thoracic wall its elasticity. The first seven pairs connect with the sternum; the next three each articulate with the lower border of the cartilage above; the last two end in the abdominal wall.',
    aliases: ['Rib Cartilage'],
    attachmentStructureIds: ['ribs', 'sternum'],
    jointId: 'sternocostal-joint',
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: false },
    difficulty: 'medium',
    tags: ['ligament'],
    clinical: 'Inflammation here is costochondritis, a common cause of chest pain that is reproduced by pressing on the joint.',
    notes: null,
  },

  // --- The buried ligaments (see the file header) ---
  //
  // THE FIVE INTEROSSEOUS LIGAMENTS OF THE WRIST ARE TAUGHT AS TWO SETS, by
  // `groups`: the proximal row (scapholunate, lunotriquetral) and the distal
  // row (the other three). They sit BETWEEN two carpal bones, so there is no
  // angle from which the strap itself can be tapped: locate asks for the gap
  // between its two bones on the bones-only carpal plate (carpal-gaps.spec.json,
  // publishGapPlates.ts), and identify shows the ligament through ghosted bones.
  {
    id: 'scapholunate-interosseous-ligament',
    name: 'Scapholunate interosseous ligament',
    category: 'ligament',
    region: 'forearm-hand',
    subregion: 'wrist-hand',
    groups: ['proximal-row-interosseous-ligaments'],
    description:
      'Joins the proximal parts of the scaphoid and the lunate inside the wrist, tying the first two bones of the proximal carpal row together. It has dorsal, palmar and membranous portions, and the dorsal portion is the strongest.',
    aliases: ['Scapholunate ligament', 'SLIL'],
    abbreviation: 'SLIL',
    attachmentStructureIds: ['scaphoid', 'lunate'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: true },
    difficulty: 'medium',
    tags: ['ligament'],
    clinical: 'When it tears the scaphoid and lunate drift apart, which is scapholunate dissociation.',
    notes: null,
  },
  {
    id: 'lunotriquetral-interosseous-ligament',
    name: 'Lunotriquetral interosseous ligament',
    category: 'ligament',
    region: 'forearm-hand',
    subregion: 'wrist-hand',
    groups: ['proximal-row-interosseous-ligaments'],
    description:
      'Joins the proximal parts of the lunate and the triquetrum inside the wrist, tying the proximal carpal row together on its ulnar side. It has dorsal, palmar and membranous portions, and here the palmar portion is the strongest.',
    aliases: ['Lunotriquetral ligament', 'LTIL'],
    abbreviation: 'LTIL',
    attachmentStructureIds: ['lunate', 'triquetrum'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: true },
    difficulty: 'medium',
    tags: ['ligament'],
    notes: null,
  },
  {
    id: 'trapeziotrapezoidal-interosseous-ligament',
    name: 'Trapeziotrapezoidal interosseous ligament',
    category: 'ligament',
    region: 'forearm-hand',
    subregion: 'wrist-hand',
    groups: ['distal-row-interosseous-ligaments'],
    description:
      'One of the three interosseous ligaments of the distal carpal row, placed between the trapezium and the trapezoid. It is the least constant of the three: Gray describes it as sometimes absent.',
    aliases: ['Trapeziotrapezoid ligament'],
    attachmentStructureIds: ['trapezium', 'trapezoid'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: true },
    difficulty: 'medium',
    tags: ['ligament'],
    notes: null,
  },
  {
    id: 'trapezoideocapitate-interosseous-ligament',
    name: 'Trapezoideocapitate interosseous ligament',
    category: 'ligament',
    region: 'forearm-hand',
    subregion: 'wrist-hand',
    groups: ['distal-row-interosseous-ligaments'],
    description:
      'One of the three interosseous ligaments of the distal carpal row, placed between the trapezoid and the capitate.',
    aliases: ['Capitotrapezoid ligament'],
    attachmentStructureIds: ['trapezoid', 'capitate'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: true },
    difficulty: 'medium',
    tags: ['ligament'],
    notes: null,
  },
  {
    id: 'capitohamate-interosseous-ligament',
    name: 'Capitohamate interosseous ligament',
    category: 'ligament',
    region: 'forearm-hand',
    subregion: 'wrist-hand',
    groups: ['distal-row-interosseous-ligaments'],
    description:
      'One of the three interosseous ligaments of the distal carpal row, placed between the capitate and the hamate. It is much the strongest of the three.',
    aliases: ['Capitohamate ligament'],
    attachmentStructureIds: ['capitate', 'hamate'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: true },
    difficulty: 'medium',
    tags: ['ligament'],
    notes: null,
  },
  {
    id: 'palmar-trapezoideocapitate-ligament',
    name: 'Palmar trapezoideocapitate ligament',
    category: 'ligament',
    region: 'forearm-hand',
    subregion: 'wrist-hand',
    description:
      'A short band running transversely across the palmar surfaces of the trapezoid and the capitate, one of the three palmar ligaments that tie the distal carpal row together.',
    aliases: [],
    attachmentStructureIds: ['trapezoid', 'capitate'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: true },
    difficulty: 'medium',
    tags: ['ligament'],
    notes: null,
  },
  // THE ANTERIOR ROOTS OF THE MENISCI. They lie flat on the tibial plateau under
  // the femur, so they are published from above only. The meniscus is listed as
  // an attachment by the same convention as the transverse ligament of the
  // knee, which lists both menisci.
  {
    id: 'anterior-meniscotibial-ligament-lateral-meniscus',
    name: 'Anterior meniscotibial ligament (Lateral meniscus)',
    category: 'ligament',
    region: 'hip-thigh',
    subregion: 'knee',
    description:
      'The anterior root of the lateral meniscus: it anchors the anterior horn of the meniscus to the tibia in front of the intercondylar eminence, lateral to and behind the anterior cruciate ligament, with which it blends.',
    aliases: ['Anterior root of the lateral meniscus'],
    attachmentStructureIds: ['lateral-meniscus', 'tibia'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: true },
    difficulty: 'medium',
    tags: ['ligament'],
    notes: null,
  },
  {
    id: 'anterior-meniscotibial-ligament-medial-meniscus',
    name: 'Anterior meniscotibial ligament (Medial meniscus)',
    category: 'ligament',
    region: 'hip-thigh',
    subregion: 'knee',
    description:
      'The anterior root of the medial meniscus: it anchors the thin, pointed anterior horn of the meniscus to the anterior intercondylar area of the tibia, in front of the anterior cruciate ligament.',
    aliases: ['Anterior root of the medial meniscus'],
    attachmentStructureIds: ['medial-meniscus', 'tibia'],
    imageIds: [],
    eligibility: { flashcard: true, mcq: true, locate: true },
    difficulty: 'medium',
    tags: ['ligament'],
    notes: null,
  },
];
